# Generated by Django 4.2 on 2026-09-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_department_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
